

export const categoryConstants = {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE'
}

export const productConstants = {
    GET_PRODUCTS_BY_SLUG: 'GET_PRODUCTS_BY_SLUG',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FROM_PRODUCTS: 'GET_ALL_PRODUCTS_FROM_PRODUCTS',
    GET_CATEGORY_PRODUCTS_BY_SEARCH_SUCCESS: 'GET_CATEGORY_PRODUCTS_BY_SEARCH_SUCCESS',
    GET_CATEGORY_PRODUCTS_BY_SEARCH_FAILURE: 'GET_CATEGORY_PRODUCTS_BY_SEARCH_FAILURE',
    GET_ALL_PRODUCTS_BY_SEARCH: 'GET_ALL_PRODUCTS_BY_SEARCH',
    GET_PRODUCTS_BY_MAIN_CATEGORY: 'GET_PRODUCTS_BY_MAIN_CATEGORY',
    GET_PRODUCTS_BY_MAIN_CATEGORY_AND_SEARCH: 'GET_PRODUCTS_BY_MAIN_CATEGORY_AND_SEARCH'
}

export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
  };
